config/routes.rb
Rails.application.routes.draw do
    root 'polls#index'
    resources :polls do
      resources :questions
    end
end

app/models/choice.rb
class Choice < ActiveRecord::Base

end

app/models/poll.rb
class Poll < ActiveRecord::Base
  has_many :questions
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :choices
	belongs_to :poll
	accepts_nested_attributes_for :choices, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController
  def index
    @polls = Poll.all
  end

  def new
    @poll = Poll.new
  end

  def create
    poll = Poll.new(poll_params)
    poll.save
    flash[:notice] = "Sondage créé : vous pouvez maintenant créer vos questions."
    redirect_to new_poll_question_path(poll)
  end

  def show
    @poll = Poll.find(params[:id])
  end

  private
  def poll_params
    params.require(:poll).permit(:title, :author, :description, :field)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :find_poll

  def new
    @question = @poll.questions.new
  end

  def create
  	question = @poll.questions.new
  	question.update_attributes(question_params)
  	question.save
  	redirect_to poll_path(@poll)
  end

  def edit
    @question = @poll.questions.find(params[:id])
  end

  def update
    question = @poll.questions.find(params[:id])
    question.choices.delete_all
    question.update_attributes(question_params)
    question.save
    redirect_to poll_path(@poll)
  end

  def destroy
    question = @poll.questions.find(params[:id])
    question.delete
    redirect_to poll_path(@poll)
  end

	private

	def question_params
		params.require(:question).permit(:content, choices_attributes: [:value, :_destroy])
	end

  def find_poll
    @poll = Poll.find(params[:poll_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def poll_title(poll)
    "#{poll.title} - #{poll.author}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Simpolls</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
  <div class="notice"><%= flash[:notice] %></div>
  <% end %>

<%= yield %>

</body>
</html>

app/views/polls/_form.html.erb
<%= form_for :polls do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :author %><br>
  <%= f.text_field :author %>
</p>
<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.label :field %><br>
  <%= f.text_area :field %>
</p>

<p>
  <%= f.submit %>
</p>
<% end %>

app/views/polls/index.html.erb
<h1>Tous les sondages</h1>
<ul>
  <% @polls.each do |p| %>
    <li><%= link_to poll_title(p), poll_path(p) %></li>
  <% end %>
</ul>
<%= link_to 'New poll', new_poll_path %>

app/views/polls/new.html.erb
<h2>Créer un nouveau sondage</h2>

<%= form_for Poll.new do |f| %>
<p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
</p>
<p>
  <%= f.label :author %><br>
  <%= f.text_field :author %>
</p>
<p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
</p>
<p>
  <%= f.submit %>
</p>
<% end %>

<%= link_to 'Annuler', polls_path %>

app/views/polls/show.html.erb
<h1><%= @poll.title %></h1>
<p><%= @poll.author %></p>
<p><%= @poll.description %></p>
<ul>
  <% @poll.questions.each do |question| %>
    <li>
      <%= question.content %> -
      <%= link_to "Supprimer la question", poll_question_path(@poll, question), method: :delete %> -
      <%= link_to "Modifier la question", edit_poll_question_path(@poll, question) %>
      <ul>
        <% question.choices.each do |choice| %>
          <li>
            <%= choice.value %>
          </li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

<ul>
  <li><%= link_to "Ajouter une question", new_poll_question_path(@poll) %></li>
  <li><%= link_to "Retour à l'accueil", root_path %></li>
  <li><%= link_to "Créer un nouveau sondage", new_poll_path %></li>
</ul>

app/views/questions/_form.html.erb
<p>
  <%= f.label :content %><br>
  <%= f.text_field :content %>
</p>
Choix possibles :
<ul>
  <%= f.fields_for :choices do |choices_form| %>
  <li>
    <%= choices_form.label :value %>
    <%= choices_form.text_field :value %>
    <%= choices_form.link_to_remove 'Supprimer ce choix' %>
  </li>
  <% end %>
  <%= f.link_to_add 'Ajouter un choix', :choices %>
</ul>
<p>
  <%= f.submit %>
</p>

app/views/questions/edit.html.erb
<h1>Modifier la question</h1>

<%= nested_form_for @question, url: poll_question_path(@poll, @question) do |f| %>

  <%= render partial: 'form', locals: {f: f} %>

<% end %>

app/views/questions/new.html.erb
<h1>Ajouter une nouvelle question</h1>

<%= nested_form_for @question, url: poll_questions_path(@poll) do |f| %>
  <%= render('form'), locals: {f: f} %>

<% end %>